name = "aiken/vesting"
version = "0.0.0"
compiler = "v1.1.7"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken/vesting'"

[repository]
user = "aiken"
project = "vesting"
platform = "github"

[[dependencies]]
name = "aiken/vesting"
version = "v2"
source = "github"

[config]
